FROM node:18-slim AS builder

WORKDIR /app

COPY package.json yarn.lock* package-lock.json* ./

RUN npm ci

COPY . .

RUN NEXT_TELEMETRY_DISABLED=1 npm run build

FROM node:18-slim AS runner

WORKDIR /app

ENV NODE_ENV production

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/public ./public

EXPOSE 3000

CMD ["npm", "start"]