version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: mongodb_logware
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: backend_logware
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/logware_db?authSource=admin
      JWT_SECRET: "seuSuperSegredoJWT"
      PORT: 5000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend_logware
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    stdin_open: true
    tty: true

volumes:
  mongodb_data:
